"""
aletheia/utils/report_generator.py

Generates executive reports (HTML + Markdown) from the full report JSON.

Fixes vs original:
  1. Gross/FCF margin double-multiplication bug in HTML (was showing 1800%)
  2. Phase 2 valuation data (3-scenario DCF, reverse DCF, Liberti multiples)
     is now fully rendered in all three report formats
  3. Constitution checks rendered with pass/fail indicators
  4. Intrinsic value now reads from phase2_valuation (not null dcf_model)
  5. WACC reads from phase2_valuation.wacc (live computed) not dcf_model

Design rule: NEVER default missing numeric values to 0.
Missing renders as "N/A" to avoid fake 0% WACC, $0 intrinsic value.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional, Sequence


class ReportGenerator:
    """
    Generates HTML + two Markdown reports from the Aletheia report JSON.
    All four report files written to serving/latest per ticker.
    """

    def __init__(self, output_dir: str = "valuation_data/serving/latest"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def generate_html(self, ticker: str, data: Dict[str, Any]) -> str:
        """Full Deep-Dive parity HTML — every section the on-screen Deep
        Dive renders is mirrored here. Page is print-friendly so browser
        ⌘P → "Save as PDF" produces a clean export."""
        meta  = data.get("generated_at") or datetime.now().isoformat()
        econ  = data.get("1_economic_reality") or {}
        fin   = data.get("2_financial_translation") or {}
        risk  = data.get("3_capital_structure_risk") or {}
        val   = data.get("4_valuation_synthesis") or {}
        thesis = val.get("investment_thesis") or {}
        thesis_synth = val.get("thesis_synthesis") or {}
        contrarian = val.get("contrarian_analysis") or {}
        p2     = val.get("phase2_valuation") or {}

        pillar_scores = thesis.get("pillar_scores") or {}
        moat = econ.get("moat") or {}
        vc   = econ.get("value_chain") or {}
        sc   = econ.get("strategic_context") or {}
        bm   = econ.get("business_model") or {}
        industry = econ.get("industry_structure") or {}

        html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Deep Dive: {ticker}</title>
  <style>{self._get_css()}</style>
</head>
<body>
  <div class="container">
    {self._render_header(ticker, meta, thesis)}
    {self._render_cyclicality_banner(industry)}
    <div class="grid-2">
      {self._render_executive_summary(thesis)}
      {self._render_valuation_card(p2, risk)}
    </div>
    {self._render_pillar_scorecard(pillar_scores)}
    {self._render_business_snapshot(bm)}
    {self._render_scenario_triangle(p2)}
    {self._render_structured_thesis(thesis_synth)}
    {self._render_phase2_section(p2)}
    {self._render_moat_detail(moat)}
    {self._render_value_chain_detail(vc)}
    {self._render_strategic_context_detail(sc)}
    {self._render_reverse_dcf_detail(p2)}
    {self._render_contrarian_block(contrarian)}
    {self._render_constitution(thesis)}
    {self._render_economic_engine(econ)}
    {self._render_financial_engine(fin)}
    {self._render_risk_engine(risk, p2)}
    <div class="footer">
      Generated by Aletheia AI | {self._safe_date(meta)} | CONFIDENTIAL
    </div>
  </div>
</body>
</html>"""

        path = self.output_dir / f"{ticker}_Executive_Report.html"
        path.write_text(html, encoding="utf-8")
        return str(path)

    # `generate_markdown` (Executive MD) was a strict subset of
    # `generate_detailed_markdown` with no unique consumer. Removed in
    # the report-consolidation pass. The Detailed MD is now the single
    # markdown surface.

    def generate_detailed_markdown(self, ticker: str, data: Dict[str, Any]) -> str:
        meta   = data.get("generated_at") or datetime.now().isoformat()
        econ   = data.get("1_economic_reality") or {}
        fin    = data.get("2_financial_translation") or {}
        risk   = data.get("3_capital_structure_risk") or {}
        val    = data.get("4_valuation_synthesis") or {}
        thesis = val.get("investment_thesis") or {}
        thesis_synth = val.get("thesis_synthesis") or {}
        p2     = val.get("phase2_valuation") or {}

        conviction = thesis.get("conviction_score")
        narrative  = (thesis.get("narrative") or "No narrative available.").strip()
        checks     = thesis.get("constitution_checks") or []

        cf     = (fin.get("clean_financials") or {})
        ratios = fin.get("ratios") or {}
        qs     = fin.get("quality_screens") or {}
        clf    = fin.get("cleaning_flags") or {}
        moat   = econ.get("moat") or {}
        vc     = econ.get("value_chain") or {}

        p2_dcf = p2.get("three_scenario_dcf") or {}
        rdcf   = p2.get("reverse_dcf") or {}
        md_dec = p2.get("multiple_decomposition") or {}
        wacc   = self._to_float(p2.get("wacc")) or \
                 self._to_float(self._get(risk, ["capital_stack", "wacc"]))

        base   = p2_dcf.get("base") or {}
        bear   = p2_dcf.get("bear") or {}
        bull   = p2_dcf.get("bull") or {}

        lines: List[str] = []

        lines += [
            f"# 📘 Detailed Valuation Report: {ticker}",
            f"**Date**: {self._safe_date(meta)}",
            "**Package**: Full Diligence",
            "**Status**: GENERATED",
            "\n---\n",
            "## 1. 📝 Investment Thesis",
            f"### Conviction Score: {conviction} (on -10 to +10 scale)",
            narrative,
            "\n---\n",
        ]

        # Structured thesis from thesis_synthesizer (Phase 1.5+). Only
        # rendered when present — legacy reports fall back to the
        # narrative summary above.
        structured_md = self._render_structured_thesis_md(thesis_synth)
        if structured_md:
            lines += [structured_md, "\n---\n"]

        # Phase 2 DCF — engine scenarios. These bound the analytically
        # defensible IV range by tilting EVERY assumption lever (terminal
        # growth, Y1-5/Y6-10 growth, terminal margin, WACC) in the same
        # direction simultaneously. They are NOT thesis-grade upside/
        # downside; they are an "all levers compounded" reference. For
        # specific-thesis IV scenarios, see the agent-proposed scenarios
        # in the thesis_synthesis section above.
        lines += [
            "## 2. 🎯 Engine DCF Scenarios (Phase 2)",
            "",
            "_Engine scenarios combine all assumption levers in one direction "
            "— they bound the analytically defensible IV range. For "
            "thesis-grade upside/downside (single-feature changes), see "
            "the agent-proposed scenarios in the structured-thesis section._",
            "",
            "| Scenario | IV/Share | Margin of Safety | EV |",
            "| :--- | :--- | :--- | :--- |",
            f"| Engine Floor (compound bear) | {self._fmt_cur(self._to_float(bear.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(bear.get('margin_of_safety')))} | {self._fmt_bn(self._to_float(bear.get('ev')) / 1e9 if bear.get('ev') else None)} |",
            f"| Engine Base (central)        | {self._fmt_cur(self._to_float(base.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(base.get('margin_of_safety')))} | {self._fmt_bn(self._to_float(base.get('ev')) / 1e9 if base.get('ev') else None)} |",
            f"| Engine Ceiling (compound bull) | {self._fmt_cur(self._to_float(bull.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(bull.get('margin_of_safety')))} | {self._fmt_bn(self._to_float(bull.get('ev')) / 1e9 if bull.get('ev') else None)} |",
            "",
            f"**WACC (live)**: {self._fmt_pct(wacc)}",
            f"**Beta (5Y weekly vs SPY)**: {self._fmt_num(self._to_float(p2.get('beta')), 2)}",
            f"**Risk-Free Rate (^TNX)**: {self._fmt_pct(self._to_float(p2.get('risk_free_rate')))}",
            "\n---\n",
        ]

        # Reverse DCF
        impl = self._to_float(rdcf.get("implied_cagr_10y"))
        hist = self._to_float(rdcf.get("historical_cagr"))
        lines += [
            "## 3. 🔍 Reverse DCF — Market Implied Growth",
            "",
            "| Metric | Value |",
            "| :--- | :--- |",
            f"| Implied 10-Year Revenue CAGR | {self._fmt_pct(impl)} |",
            f"| Historical CAGR (robust median) | {self._fmt_pct(hist)} |",
            f"| Ratio (Implied / Historical) | {self._fmt_ratio(rdcf)} |",
            f"| Signal | {(rdcf.get('signal') or 'N/A').upper()} |",
        ]
        for reason in (rdcf.get("reasons") or []):
            lines.append(f"\n> {reason}")
        lines.append("\n---\n")

        # Multiple decomposition
        lines += [
            "## 4. 📐 Multiple Decomposition (Liberti Formula)",
            "",
            "> EV/EBITDA = [NOPAT×(1−g/ROIC)/EBITDA] ÷ (WACC−g)",
            "",
            "| Metric | Value |",
            "| :--- | :--- |",
            f"| Market EV/EBITDA | {self._fmt_num(self._to_float(md_dec.get('market_ev_ebitda')), 1)}× |",
            f"| Justified EV/EBITDA (Liberti) | {self._fmt_num(self._to_float(md_dec.get('justified_ev_ebitda')), 1)}× |",
            f"| Premium to Justified | {self._fmt_pct(self._to_float(md_dec.get('premium_pct')))} |",
            f"| ROIC | {self._fmt_pct(self._to_float(md_dec.get('roic')))} |",
            f"| WACC | {self._fmt_pct(wacc)} |",
            f"| ROIC−WACC Spread | {self._fmt_pct(self._to_float(md_dec.get('roic_wacc_spread')))} |",
            f"| Value Creation | {(md_dec.get('value_creation') or 'N/A').upper()} |",
            f"| Signal | {(md_dec.get('signal') or 'N/A').upper()} |",
            "\n---\n",
        ]

        # Constitution
        lines += [
            "## 5. ⚖️ Constitution Checks",
            "",
            self._fmt_checks_md(checks),
            "\n---\n",
        ]

        # Fundamentals
        lines += [
            "## 6. 💹 Financial Analysis (Phase 1 Cleaned)",
            "### Core P&L (TTM)",
            "| Line Item | Value |",
            "| :--- | :--- |",
            f"| Revenue | {self._fmt_bn(cf.get('revenue_bn'))} |",
            f"| EBITDA | {self._fmt_bn(cf.get('ebitda_bn'))} |",
            f"| FCF | {self._fmt_bn(cf.get('fcf_bn'))} |",
            f"| NOPAT | {self._fmt_bn(cf.get('nopat_bn'))} |",
            "",
            "### Balance Sheet",
            "| Line Item | Value |",
            "| :--- | :--- |",
            f"| Net Debt | {self._fmt_bn(cf.get('net_debt_bn'))} |",
            f"| Invested Capital | {self._fmt_bn(cf.get('invested_capital_bn'))} |",
            f"| SBC | {self._fmt_bn(cf.get('sbc_bn'))} |",
            f"| Data Quality Score | {self._fmt_num(self._to_float(cf.get('data_quality')), 2)} |",
            "",
            "### Efficiency Ratios",
            "| Ratio | Value |",
            "| :--- | :--- |",
            f"| Gross Margin | {self._fmt_ratio_pct(ratios.get('gross_margin_pct'))} |",
            f"| EBIT Margin | {self._fmt_ratio_pct(ratios.get('ebit_margin_pct'))} |",
            f"| EBITDA Margin | {self._fmt_ratio_pct(ratios.get('ebitda_margin_pct'))} |",
            f"| FCF Margin | {self._fmt_ratio_pct(ratios.get('fcf_margin_pct'))} |",
            f"| ROIC | {self._fmt_pct(self._to_float(ratios.get('roic')))} |",
            f"| ROE | {self._fmt_pct(self._to_float(ratios.get('roe')))} |",
            f"| SBC % FCF | {self._fmt_ratio_pct(ratios.get('sbc_pct_fcf'))} |",
            f"| Cash Tax Rate | {self._fmt_pct(self._to_float(ratios.get('cash_tax_rate')))} |",
            "\n---\n",
        ]

        # Domain scores
        domain_scores = qs.get("domain_scores") or {}
        if domain_scores:
            lines += [
                "## 7. 🧹 Data Cleaning Quality (9-Domain)",
                "",
                "| Domain | Score |",
                "| :--- | :--- |",
            ]
            domain_labels = {
                "D1_NonRecurring": "D1 Non-Recurring Stripping",
                "D2_JVA": "D2 JVA Separation",
                "D3_EBITNorm": "D3 EBIT Normalization",
                "D4_AccountingPolicy": "D4 Accounting Policy",
                "D5_Lease": "D5 Lease Normalization",
                "D6_Pension": "D6 Pension Cleaning",
                "D7_SBC": "D7 SBC Adjustment",
                "D8_Revenue": "D8 Revenue Recognition",
                "D9_WorkingCapital": "D9 Working Capital",
                "D10_Tax": "D10 Tax Sustainability",
            }
            for key, score in sorted(domain_scores.items()):
                label = domain_labels.get(key, key)
                score_v = self._to_float(score)
                icon = "✅" if score_v and score_v >= 0.9 else "⚠️" if score_v and score_v >= 0.7 else "❌"
                lines.append(f"| {icon} {label} | {self._fmt_num(score_v, 2)} |")

            warn  = clf.get("warning_count", 0)
            err   = clf.get("error_count", 0)
            lines += ["", f"**Warnings**: {warn}  |  **Errors**: {err}", "\n---\n"]

        # Economic reality
        lines += [
            "## 8. 🌎 Economic Reality & Moat",
            f"### Moat Score: {moat.get('score', 'N/A')}/10",
            f"- Switching Costs: {moat.get('switching_costs', 'N/A')}",
            f"- Network Effects: {moat.get('network_effects', 'N/A')}",
            "",
            "### Value Chain",
            f"- Power Ratio: {vc.get('power_ratio', 'N/A')}",
            f"- Upstream Value Leak: {vc.get('upstream_leak', 'N/A')}",
            f"- Strategic Leverage: {vc.get('strategic_leverage', 'N/A')}",
            "\n---\n",
        ]

        # Capital structure
        cap = risk.get("capital_stack") or {}
        rf_data = risk.get("risk_factors") or {}
        liq = rf_data.get("liquidity") or {}
        lines += [
            "## 9. 🛡️ Capital Structure & Risk",
            f"- WACC: {self._fmt_pct(self._to_float(cap.get('wacc')))}",
            f"- Cost of Equity: {self._fmt_pct(self._to_float(cap.get('cost_of_equity')))}",
            f"- Beta: {self._fmt_num(self._to_float(cap.get('beta')), 2)}",
            f"- Liquidity Alert: {liq.get('liquidity_alert', False)}",
            f"- Refinancing Risk Score: {liq.get('refinancing_risk_score', 'N/A')}/10",
        ]

        md = "\n".join(lines)
        path = self.output_dir / f"{ticker}_Detailed_Report.md"
        path.write_text(md, encoding="utf-8")
        return str(path)

    # ─────────────────────────────────────────────────────────────────────────
    # HTML section renderers
    # ─────────────────────────────────────────────────────────────────────────

    def _render_header(self, ticker: str, meta: str, thesis: Dict[str, Any]) -> str:
        conviction = thesis.get("conviction_score")
        conv_num   = int(conviction) if conviction is not None else 0
        color = "#27ae60" if conv_num >= 3 else "#f39c12" if conv_num >= 0 else "#c0392b"
        return f"""
<div style="display:flex;justify-content:space-between;align-items:center">
  <div>
    <h1>{ticker} Investment Memo</h1>
    <div style="color:#7f8c8d">Generated on {self._safe_date(meta)}</div>
  </div>
  <div style="text-align:center">
    <div class="score-circle" style="background:{color}">{conv_num:+d}</div>
    <div style="margin-top:5px;font-weight:bold">CONVICTION</div>
  </div>
</div>""".strip()

    def _render_executive_summary(self, thesis: Dict[str, Any]) -> str:
        narrative = (thesis.get("narrative") or "No narrative available.").replace("\n", "<br>")
        return f"""
<div class="card">
  <h3>📝 Executive Summary</h3>
  <p style="line-height:1.6">{narrative}</p>
</div>""".strip()

    def _render_structured_thesis(self, ts: Dict[str, Any]) -> str:
        """Full thesis_synthesizer output: bull/base/bear cases with
        cited_signals, decision_conditions, update_conditions, confidence,
        time_horizon. Empty string if no thesis_synthesis (legacy reports
        pre-Phase 1.5)."""
        if not ts or not ts.get("thesis_statement"):
            return ""

        statement = ts.get("thesis_statement", "")
        confidence = (ts.get("thesis_confidence") or "—").upper()
        horizon = (ts.get("time_horizon") or "—").replace("_", " ").upper()
        conf_color = {
            "HIGH": "#10b981", "MEDIUM": "#f59e0b", "LOW": "#ef4444",
            "INSUFFICIENT_SIGNAL": "#a1a1aa",
        }.get(confidence, "#a1a1aa")

        case_blocks = []
        for label, key, color in [
            ("BULL CASE", "bull_case", "#10b981"),
            ("BASE CASE", "base_case", "#f59e0b"),
            ("BEAR CASE", "bear_case", "#ef4444"),
        ]:
            cc = ts.get(key) or {}
            claim = cc.get("claim", "") or ""
            if not claim:
                continue
            cites = cc.get("cited_signals") or []
            cite_chips = ""
            if cites:
                # `display:inline-block` + `white-space:nowrap` keeps each
                # chip as one cohesive token (so spaces inside citation
                # paths like "Housing Turnover Rebound" don't split the
                # chip mid-word). Parent `display:flex; flex-wrap:wrap`
                # handles row breaks BETWEEN chips instead of letting them
                # overflow the card's right edge — the bug fix here.
                chips = "".join(
                    f'<span style="display:inline-block;white-space:nowrap;'
                    f'font-family:monospace;font-size:10px;'
                    f'color:#71717a;background:#f4f4f5;padding:2px 6px;'
                    f'border-radius:3px;">{c}</span>'
                    for c in cites
                )
                cite_chips = (
                    f'<div style="margin-top:8px;display:flex;flex-wrap:wrap;'
                    f'align-items:baseline;gap:4px;">'
                    f'<span style="font-family:monospace;font-size:10px;'
                    f'color:#71717a;text-transform:uppercase;letter-spacing:0.5px;'
                    f'margin-right:4px;">Cites:</span>{chips}</div>'
                )
            case_blocks.append(
                f'<div style="border:1px solid #e4e4e7;border-left:4px solid {color};'
                f'padding:14px 18px;border-radius:0 6px 6px 0;margin-bottom:10px;">'
                f'<div style="font-family:monospace;font-size:11px;'
                f'color:{color};letter-spacing:0.7px;text-transform:uppercase;'
                f'margin-bottom:6px;font-weight:700;">{label}</div>'
                f'<div style="font-size:14px;line-height:1.7;">{claim}</div>'
                f'{cite_chips}</div>'
            )

        # Decision conditions table
        dcs = ts.get("decision_conditions") or []
        dc_rows = []
        action_color = {
            "EXIT": "#ef4444", "TRIM": "#ef4444", "SELL": "#ef4444", "PASS": "#ef4444",
            "HOLD": "#f59e0b", "WATCH": "#f59e0b", "REVIEW": "#f59e0b",
            "ADD": "#10b981", "BUY": "#10b981", "ACCUMULATE": "#10b981",
        }
        priority_color = {"red": "#ef4444", "amber": "#f59e0b", "green": "#10b981"}
        for dc in dcs:
            pri = (dc.get("priority") or "").lower()
            act = (dc.get("action") or "").upper()
            trigger = dc.get("trigger", "") or "—"
            obs = dc.get("observable", "") or ""
            p_color = priority_color.get(pri, "#a1a1aa")
            a_color = action_color.get(act, "#a1a1aa")
            dc_rows.append(
                f'<tr style="border-bottom:1px solid #e4e4e7">'
                f'<td style="padding:8px 12px;color:{p_color};font-family:monospace;'
                f'font-size:11px;font-weight:700;text-transform:uppercase;">● {pri or "—"}</td>'
                f'<td style="padding:8px 12px;font-size:13px;">{trigger}'
                f'<div style="font-family:monospace;font-size:11px;color:#71717a;'
                f'margin-top:4px;">{obs}</div></td>'
                f'<td style="padding:8px 12px;text-align:right;">'
                f'<span style="font-family:monospace;font-size:10px;font-weight:700;'
                f'letter-spacing:0.6px;color:{a_color};border:1px solid {a_color};'
                f'padding:3px 9px;border-radius:3px;">{act or "—"}</span></td>'
                f'</tr>'
            )
        dc_table = ""
        if dc_rows:
            dc_table = (
                f'<h4 style="margin-top:18px;">Decision Conditions</h4>'
                f'<table style="width:100%;border-collapse:collapse;'
                f'border:1px solid #e4e4e7;border-radius:6px;overflow:hidden;">'
                f'<thead><tr style="background:#f4f4f5;">'
                f'<th style="padding:10px 12px;text-align:left;font-size:11px;'
                f'text-transform:uppercase;letter-spacing:0.5px;color:#71717a;">Priority</th>'
                f'<th style="padding:10px 12px;text-align:left;font-size:11px;'
                f'text-transform:uppercase;letter-spacing:0.5px;color:#71717a;">Trigger / Observable</th>'
                f'<th style="padding:10px 12px;text-align:right;font-size:11px;'
                f'text-transform:uppercase;letter-spacing:0.5px;color:#71717a;">Action</th>'
                f'</tr></thead>'
                f'<tbody>{"".join(dc_rows)}</tbody></table>'
            )

        # Required analyst judgment + Update conditions
        raj = ts.get("required_analyst_judgment") or []
        upd = ts.get("update_conditions") or []
        side_blocks = ""
        if raj or upd:
            raj_html = ""
            if raj:
                raj_html = (
                    f'<div style="flex:1;"><h4>Required Analyst Judgment</h4>'
                    f'<p style="font-size:12px;color:#71717a;margin-top:-6px;">'
                    f'Gaps the framework defers to the analyst</p>'
                    f'<ul style="font-size:13px;line-height:1.6;">'
                    + "".join(f"<li>{r}</li>" for r in raj) + "</ul></div>"
                )
            upd_html = ""
            if upd:
                upd_html = (
                    f'<div style="flex:1;"><h4>Update Conditions</h4>'
                    f'<p style="font-size:12px;color:#71717a;margin-top:-6px;">'
                    f'What would invalidate this thesis</p>'
                    f'<ul style="font-size:13px;line-height:1.6;">'
                    + "".join(f"<li>{u}</li>" for u in upd) + "</ul></div>"
                )
            side_blocks = (
                f'<div style="display:flex;gap:24px;margin-top:18px;">'
                f'{raj_html}{upd_html}</div>'
            )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>🧭 Structured Investment Thesis</h3>
  <div style="font-family:monospace;font-size:11px;color:#71717a;
              margin-bottom:12px;letter-spacing:0.3px;">
    Confidence: <span style="color:{conf_color};font-weight:700">{confidence}</span>
    &nbsp;·&nbsp;
    Horizon: <span style="font-weight:700">{horizon}</span>
  </div>
  <div style="border-left:4px solid {conf_color};padding:14px 20px;
              background:#fafafa;border-radius:0 6px 6px 0;
              font-size:15px;line-height:1.7;margin-bottom:18px;font-weight:500;">
    {statement}
  </div>
  {"".join(case_blocks)}
  {dc_table}
  {side_blocks}
</div>""".strip()

    def _render_valuation_card(self, p2: Dict[str, Any], risk: Dict[str, Any]) -> str:
        dcf3 = p2.get("three_scenario_dcf") or {}
        base = dcf3.get("base") or {}
        bear = dcf3.get("bear") or {}
        bull = dcf3.get("bull") or {}
        base_iv  = self._to_float(base.get("intrinsic_per_share"))
        base_mos = self._to_float(base.get("margin_of_safety"))
        wacc = self._to_float(p2.get("wacc")) or \
               self._to_float(self._get(risk, ["capital_stack", "wacc"]))
        rdcf = p2.get("reverse_dcf") or {}
        impl = self._to_float(rdcf.get("implied_cagr_10y"))
        hist = self._to_float(rdcf.get("historical_cagr"))

        mos_color = "green" if base_mos and base_mos > 0 else "red"

        # Engine scenarios bound the analytically defensible IV range by
        # tilting all assumption levers in one direction simultaneously.
        # See the structured-thesis section (above) for thesis-grade
        # upside/downside scenarios proposed by upstream agents.
        return f"""
<div class="card">
  <h3>🎯 Valuation Synthesis (Phase 2)</h3>
  <div class="metric-box" style="margin-bottom:10px">
    <span class="metric-val" style="color:{mos_color}">{self._fmt_pct(base_mos)}</span>
    <span class="metric-label">Base Margin of Safety</span>
  </div>
  <table class="table-styled">
    <tr><td title="Compound bear: every assumption lever tilted bear">Engine Floor / Share</td>
        <td style="font-weight:bold">{self._fmt_cur(self._to_float(bear.get('intrinsic_per_share')))}</td></tr>
    <tr><td title="Central case">Engine Base / Share</td>
        <td style="font-weight:bold;color:{mos_color}">{self._fmt_cur(base_iv)}</td></tr>
    <tr><td title="Compound bull: every assumption lever tilted bull">Engine Ceiling / Share</td>
        <td style="font-weight:bold">{self._fmt_cur(self._to_float(bull.get('intrinsic_per_share')))}</td></tr>
    <tr><td>WACC (live)</td><td>{self._fmt_pct(wacc)}</td></tr>
    <tr><td>Implied CAGR</td><td>{self._fmt_pct(impl)}</td></tr>
    <tr><td>Historical CAGR</td><td>{self._fmt_pct(hist)}</td></tr>
  </table>
  <div style="font-size:0.78em;color:#7f8c8d;margin-top:8px;line-height:1.5">
    Engine scenarios combine all assumption levers in one direction —
    they bound the analytically defensible range. For thesis-grade
    upside/downside, see the structured-thesis section.
  </div>
</div>""".strip()

    def _render_phase2_section(self, p2: Dict[str, Any]) -> str:
        rdcf   = p2.get("reverse_dcf") or {}
        md_dec = p2.get("multiple_decomposition") or {}

        impl   = self._to_float(rdcf.get("implied_cagr_10y"))
        hist   = self._to_float(rdcf.get("historical_cagr"))
        signal = (rdcf.get("signal") or "").upper()

        ev_market = self._to_float(md_dec.get("market_ev_ebitda"))
        ev_just   = self._to_float(md_dec.get("justified_ev_ebitda"))
        premium   = self._to_float(md_dec.get("premium_pct"))
        spread    = self._to_float(md_dec.get("roic_wacc_spread"))
        vc_signal = (md_dec.get("signal") or "").upper()

        spread_color = "#27ae60" if spread and spread > 0 else "#c0392b"
        prem_color   = "#c0392b" if premium and premium > 0 else "#27ae60"

        reasons_html = "".join(
            f"<li style='margin-bottom:6px'>{r}</li>"
            for r in (rdcf.get("reasons") or [])
        )

        return f"""
<h2>Phase 2: Quantitative Valuation Intelligence</h2>
<div class="grid-2">
  <div class="card">
    <h4>🔍 Reverse DCF — What Is the Market Pricing In?</h4>
    <table class="table-styled">
      <tr><td>Implied 10Y CAGR</td><td style="font-weight:bold">{self._fmt_pct(impl)}</td></tr>
      <tr><td>Historical CAGR</td><td>{self._fmt_pct(hist)}</td></tr>
      <tr><td>Ratio (Impl/Hist)</td><td style="color:{('#c0392b' if impl and hist and impl/hist > 1.5 else '#27ae60')}">{self._fmt_ratio(rdcf)}</td></tr>
      <tr><td>Signal</td><td><b>{signal}</b></td></tr>
    </table>
    {"<ul style='font-size:0.85em;padding-left:18px;margin-top:10px;color:#555'>" + reasons_html + "</ul>" if reasons_html else ""}
  </div>
  <div class="card">
    <h4>📐 Multiple Decomposition (Liberti Formula)</h4>
    <div style="font-size:0.8em;color:#888;margin-bottom:8px">
      EV/EBITDA = [NOPAT×(1−g/ROIC)/EBITDA] ÷ (WACC−g)
    </div>
    <table class="table-styled">
      <tr><td>Market EV/EBITDA</td><td style="font-weight:bold">{self._fmt_num(ev_market, 1)}×</td></tr>
      <tr><td>Justified EV/EBITDA</td><td style="color:#27ae60">{self._fmt_num(ev_just, 1)}×</td></tr>
      <tr><td>Premium to Justified</td><td style="color:{prem_color}">{self._fmt_pct(premium)}</td></tr>
      <tr><td>ROIC−WACC Spread</td><td style="color:{spread_color}">{self._fmt_pct(spread)}</td></tr>
      <tr><td>Signal</td><td><b>{vc_signal}</b></td></tr>
    </table>
  </div>
</div>""".strip()

    def _render_constitution(self, thesis: Dict[str, Any]) -> str:
        checks = thesis.get("constitution_checks") or []
        if not checks:
            return ""

        rows = ""
        for check in checks:
            check_str = str(check)
            is_pass   = "PASS" in check_str or "✅" in check_str
            is_warn   = "CAUTION" in check_str or "⚠" in check_str
            bg     = "#d5f5e3" if is_pass else "#fef9e7" if is_warn else "#fadbd8"
            border = "#27ae60" if is_pass else "#f39c12" if is_warn else "#c0392b"
            icon   = "✅" if is_pass else "⚠️" if is_warn else "❌"
            # Clean up unicode escape sequences
            clean = check_str.replace("✅", "").replace("❌", "").replace("⚠️", "").strip()
            rows += f"""<tr style="background:{bg};border-left:4px solid {border}">
              <td style="padding:8px 6px;font-size:1.3em">{icon}</td>
              <td style="padding:8px">{clean}</td>
            </tr>"""

        return f"""
<h2>⚖️ Constitution Compliance</h2>
<div class="card" style="padding:0;overflow:hidden">
  <table class="table-styled" style="margin:0">
    <thead><tr>
      <th style="width:40px"></th>
      <th>Check</th>
    </tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>""".strip()

    def _render_economic_engine(self, econ: Dict[str, Any]) -> str:
        moat = econ.get("moat") or {}
        vc   = econ.get("value_chain") or {}
        ind  = econ.get("industry_structure") or {}

        moat_score = int(moat.get("score") or 0)
        moat_color = "#27ae60" if moat_score >= 9 else "#f39c12" if moat_score >= 7 else "#c0392b"

        return f"""
<h2>1. 🌎 Economic Reality Engine</h2>
<div class="grid-3">
  <div class="card">
    <h4>🏰 Moat Assessment</h4>
    <div class="metric-box">
      <span class="metric-val" style="color:{moat_color}">{moat_score}/10</span>
      <span class="metric-label">Moat Score (Helmer 7 Powers)</span>
    </div>
    <ul style="font-size:0.9em;padding-left:20px;margin-top:10px">
      <li>Switching Costs: <b>{moat.get('switching_costs', 'N/A')}</b></li>
      <li>Network Effects: <b>{moat.get('network_effects', 'N/A')}</b></li>
    </ul>
  </div>
  <div class="card">
    <h4>🔗 Value Chain (Porter)</h4>
    <table class="table-styled">
      <tr><td>Power Ratio</td><td>{vc.get('power_ratio', 'N/A')}</td></tr>
      <tr><td>Upstream Leak</td>
        <td style="color:{'#c0392b' if vc.get('upstream_leak') else '#27ae60'}">
          {'⚠ YES' if vc.get('upstream_leak') else '✓ NO'}
        </td>
      </tr>
      <tr><td>Strategic Leverage</td><td>{vc.get('strategic_leverage', 'N/A')}</td></tr>
    </table>
  </div>
  <div class="card">
    <h4>📊 Industry Structure</h4>
    <table class="table-styled">
      <tr><td>Cyclicality Z-Score</td><td>{self._fmt_num(self._to_float(ind.get('cyclicality_z_score')), 2)}</td></tr>
      <tr><td>At Cyclical Peak</td>
        <td style="color:{'#c0392b' if ind.get('is_peak') else '#27ae60'}">
          {'⚠ YES' if ind.get('is_peak') else '✓ NO'}
        </td>
      </tr>
    </table>
  </div>
</div>""".strip()

    def _render_financial_engine(self, fin: Dict[str, Any]) -> str:
        cf     = (fin.get("clean_financials") or {})
        ratios = fin.get("ratios") or {}

        # FIX: gross_margin_pct is stored as % (e.g. 18.0), not decimal.
        # _fmt_ratio_pct handles this correctly — divides by 100 before formatting.
        return f"""
<h2>2. 💹 Financial Translation (Phase 1 Cleaned)</h2>
<div class="card">
  <div class="grid-3">
    <div>
      <h4>Core P&L (TTM)</h4>
      <table class="table-styled">
        <tr><td>Revenue</td><td>{self._fmt_bn(cf.get('revenue_bn'))}</td></tr>
        <tr><td>EBITDA</td><td>{self._fmt_bn(cf.get('ebitda_bn'))}</td></tr>
        <tr><td>FCF</td><td>{self._fmt_bn(cf.get('fcf_bn'))}</td></tr>
        <tr><td>NOPAT</td><td>{self._fmt_bn(cf.get('nopat_bn'))}</td></tr>
      </table>
    </div>
    <div>
      <h4>Balance Sheet</h4>
      <table class="table-styled">
        <tr><td>Net Debt</td><td>{self._fmt_bn(cf.get('net_debt_bn'))}</td></tr>
        <tr><td>Invested Capital</td><td>{self._fmt_bn(cf.get('invested_capital_bn'))}</td></tr>
        <tr><td>SBC</td><td>{self._fmt_bn(cf.get('sbc_bn'))}</td></tr>
      </table>
    </div>
    <div>
      <h4>Efficiency Ratios</h4>
      <table class="table-styled">
        <tr><td>Gross Margin</td><td>{self._fmt_ratio_pct(ratios.get('gross_margin_pct'))}</td></tr>
        <tr><td>EBIT Margin</td><td>{self._fmt_ratio_pct(ratios.get('ebit_margin_pct'))}</td></tr>
        <tr><td>FCF Margin</td><td>{self._fmt_ratio_pct(ratios.get('fcf_margin_pct'))}</td></tr>
        <tr><td>ROIC</td><td>{self._fmt_pct(self._to_float(ratios.get('roic')))}</td></tr>
        <tr><td>ROE</td><td>{self._fmt_pct(self._to_float(ratios.get('roe')))}</td></tr>
      </table>
    </div>
  </div>
</div>""".strip()

    def _render_risk_engine(self, risk: Dict[str, Any], p2: Dict[str, Any] = None) -> str:
        cap = risk.get("capital_stack") or {}
        rf  = (risk.get("risk_factors") or {}).get("liquidity") or {}
        ds  = (risk.get("risk_factors") or {}).get("downside") or {}

        # WACC display: prefer phase2.wacc (canonical, used by DCF math
        # AND by the dashboard) over capital_stack.wacc (which carries a
        # 9% hard floor that creates a visible mismatch). Fall back to
        # capital_stack.wacc only if phase2.wacc is missing.
        p2_wacc = self._to_float((p2 or {}).get("wacc"))
        cap_wacc = self._to_float(cap.get('wacc'))
        wacc_display = p2_wacc if p2_wacc else cap_wacc

        return f"""
<h2>3. 🛡️ Capital Structure & Risk</h2>
<div class="grid-2">
  <div class="card">
    <h4>💰 Capital Stack</h4>
    <table class="table-styled">
      <tr><td>WACC</td><td>{self._fmt_pct(wacc_display)}</td></tr>
      <tr><td>Cost of Equity</td><td>{self._fmt_pct(self._to_float(cap.get('cost_of_equity')))}</td></tr>
      <tr><td>Beta</td><td>{self._fmt_num(self._to_float(cap.get('beta')), 2)}</td></tr>
    </table>
    <h4 style="margin-top:12px">⚠️ Liquidity</h4>
    <table class="table-styled">
      <tr><td>Liquidity Alert</td>
        <td style="color:{'#c0392b' if rf.get('liquidity_alert') else '#27ae60'}">
          {'⚠ YES' if rf.get('liquidity_alert') else '✓ NO'}
        </td>
      </tr>
      <tr><td>Refinancing Risk</td><td>{rf.get('refinancing_risk_score', 'N/A')}/10</td></tr>
    </table>
  </div>
  <div class="card">
    <h4>📉 Downside Protection</h4>
    <table class="table-styled">
      <tr><td>Tangible Book Value</td><td>{self._fmt_cur(self._to_float(ds.get('tangible_book_value')))}</td></tr>
      <tr><td>Earnings Power Value</td><td>{self._fmt_cur(self._to_float(ds.get('earnings_power_value')))}</td></tr>
      <tr><td>Floor Value</td><td>{self._fmt_cur(self._to_float(ds.get('floor_value')))}</td></tr>
    </table>
  </div>
</div>""".strip()

    # ─────────────────────────────────────────────────────────────────────────
    # Deep-Dive parity renderers — mirror the on-screen Deep Dive sections
    # that the legacy executive HTML lacked. Same data sources, same field
    # names; styling adapted to the static-HTML CSS framework.
    # ─────────────────────────────────────────────────────────────────────────

    _PILLAR_DEFS = [
        ("Moat",             "p1_moat",       "Durability of competitive advantage"),
        ("Health",           "p2_health",     "Balance sheet + cash flow durability"),
        ("Tailwind",         "p3_tailwind",   "Industry/macro structural growth"),
        ("Margin of Safety", "p4_mos",        "Discount of price to intrinsic value"),
        ("Leadership",       "p5_leadership", "Capital allocation + management quality"),
    ]

    def _render_cyclicality_banner(self, industry: Dict[str, Any]) -> str:
        """Top-of-page banner when a ticker is at a cyclical peak.
        Z-score >2 means current cycle position is two standard
        deviations above long-run mean."""
        if not industry:
            return ""
        z = self._to_float(industry.get("cyclicality_z_score"))
        is_peak = bool(industry.get("is_peak"))
        if z is None and not is_peak:
            return ""
        if not is_peak and (z is None or abs(z) < 2):
            return ""
        z_str = f"{z:+.2f}σ" if z is not None else "—"
        return (
            f'<div style="background:#fef9e7;border-left:4px solid #f39c12;'
            f'padding:12px 16px;border-radius:0 6px 6px 0;margin:12px 0;'
            f'font-size:13px;">'
            f'<strong style="color:#b9770e">⚠ Cyclical-peak signal:</strong> '
            f'cyclicality z-score {z_str} '
            f'{"(at/near peak)" if is_peak else "(historically elevated)"}'
            f'</div>'
        )

    def _render_pillar_scorecard(self, ps: Dict[str, Any]) -> str:
        """5-pillar horizontal-bar scorecard. Mirrors deep_dive_view._pillar_section."""
        if not ps:
            return ""
        capped = ps.get("capped_total", "—")
        tier   = (ps.get("position_tier") or "—").upper()
        position_size = self._to_float(ps.get("position_size_pct"))
        position_size_str = f"{position_size*100:.1f}%" if position_size else "—"

        rows = []
        for name, key, hint in self._PILLAR_DEFS:
            raw = ps.get(key)
            if isinstance(raw, dict):
                score = raw.get("score") or 0
            else:
                score = float(raw or 0)
            score_norm = max(0, min(int(score), 5))
            color = "#27ae60" if score >= 4 else "#f39c12" if score >= 2 else "#c0392b"
            # 5 segments — colored up to score, neutral track for the rest
            segs = "".join(
                f'<span style="display:inline-block;width:34px;height:13px;'
                f'background:{color if i <= score_norm else "#e4e4e7"};'
                f'margin-right:3px;border-radius:3px"></span>'
                for i in range(1, 6)
            )
            # Reasons: pulled from p<n>_reasons sibling key
            reasons_key = key.replace("_moat","").replace("_health","").replace(
                "_tailwind","").replace("_mos","").replace("_leadership","")
            reasons_list = ps.get(f"{reasons_key}_reasons")
            reason_html = ""
            if isinstance(reasons_list, list) and reasons_list:
                items = "".join(f"<li>{r}</li>" for r in reasons_list[:3])
                reason_html = (
                    f'<ul style="margin:4px 0 0 174px;padding-left:18px;'
                    f'color:#71717a;font-size:11.5px;line-height:1.5;">{items}</ul>'
                )
            rows.append(
                f'<div style="display:flex;align-items:center;gap:14px;'
                f'padding:8px 0;border-bottom:1px solid #f4f4f5;">'
                f'<div style="flex-basis:150px;font-size:13px;font-weight:600;">{name}</div>'
                f'<div style="flex-basis:200px">{segs}</div>'
                f'<div style="flex-basis:48px;text-align:right;color:{color};'
                f'font-family:monospace;font-weight:700;font-size:13px">{int(score)}/5</div>'
                f'<div style="flex:1;color:#71717a;font-size:12px">{hint}</div>'
                f'</div>{reason_html}'
            )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>🏛️ Pillar Scorecard
    <span style="font-family:monospace;font-size:13px;color:#71717a;font-weight:400;
                 margin-left:10px;">total {capped}/25 · tier {tier} · size {position_size_str}</span>
  </h3>
  {"".join(rows)}
</div>""".strip()

    def _render_business_snapshot(self, bm: Dict[str, Any]) -> str:
        """Business model: description + KPI strip + revenue segments + key customers
        + competitive landscape + cost structure + regulatory risk. Mirrors
        deep_dive_view._business_snapshot."""
        if not bm:
            return ""
        desc = bm.get("business_description") or ""
        op_lev = self._to_float(bm.get("operating_leverage_score"))
        segs = bm.get("revenue_segments") or []
        custs = bm.get("key_customers") or []

        desc_html = (
            f'<div style="background:#fafafa;padding:14px 16px;border-radius:6px;'
            f'font-size:14px;line-height:1.6;margin-bottom:14px;">{desc}</div>'
            if desc else ""
        )

        kpi_strip = (
            f'<div style="display:grid;grid-template-columns:repeat(3,1fr);'
            f'gap:14px;margin-bottom:14px;">'
            f'<div class="metric-box"><span class="metric-val">'
            f'{f"{op_lev:.1f}/10" if op_lev is not None else "—"}</span>'
            f'<span class="metric-label">Operating leverage</span></div>'
            f'<div class="metric-box"><span class="metric-val">{len(segs) or "—"}</span>'
            f'<span class="metric-label">Revenue segments</span></div>'
            f'<div class="metric-box"><span class="metric-val">{len(custs) or "—"}</span>'
            f'<span class="metric-label">Disclosed key customers</span></div>'
            f'</div>'
        )

        # Revenue segments table
        seg_html = ""
        if segs:
            seg_rows = []
            for s in segs:
                pct = self._to_float(s.get("pct_revenue"))
                pct_str = f"{pct:.1f}%" if pct is not None else "—"
                bar_width = min(max(pct or 0, 0), 100)
                seg_rows.append(
                    f'<tr><td>{s.get("segment", "—")}</td>'
                    f'<td style="width:280px"><div style="background:#e4e4e7;'
                    f'border-radius:3px;height:14px;width:200px;display:inline-block;'
                    f'vertical-align:middle;margin-right:6px;"><div style="background:#27ae60;'
                    f'height:14px;width:{bar_width*2}px;border-radius:3px;"></div></div>'
                    f'<span style="font-family:monospace;font-size:12px;">{pct_str}</span></td>'
                    f'<td style="text-transform:uppercase;font-family:monospace;'
                    f'font-size:11px;color:#71717a;">'
                    f'{s.get("growth_trend") or "—"}</td></tr>'
                )
            seg_html = (
                f'<h4>Revenue segments</h4>'
                f'<table class="table-styled">'
                f'<thead><tr><th>Segment</th><th>% of revenue</th><th>Trend</th></tr></thead>'
                f'<tbody>{"".join(seg_rows)}</tbody></table>'
            )

        # Customers + narrative fields
        cust_html = ""
        if custs:
            cust_html = (
                f'<h4 style="margin-top:14px">Key customers</h4>'
                f'<ul style="font-size:13px;line-height:1.6;">'
                + "".join(f"<li>{c}</li>" for c in custs) + "</ul>"
            )
        narrative_html = ""
        for label, key in [
            ("Competitive landscape", "competitive_landscape"),
            ("Cost structure",        "cost_structure"),
            ("Regulatory risk",       "regulatory_risk"),
        ]:
            v = bm.get(key)
            if v:
                narrative_html += (
                    f'<h4 style="margin-top:14px">{label}</h4>'
                    f'<div style="font-size:13px;line-height:1.6;color:#3f3f46;">{v}</div>'
                )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>🏢 Business Snapshot</h3>
  {desc_html}
  {kpi_strip}
  {seg_html}
  {cust_html}
  {narrative_html}
</div>""".strip()

    def _render_scenario_triangle(self, p2: Dict[str, Any]) -> str:
        """Bull/Base/Bear IV horizontal-bar chart. Pure HTML/CSS — no JS dep."""
        dcf3 = p2.get("three_scenario_dcf") or {}
        bear = dcf3.get("bear") or {}
        base = dcf3.get("base") or {}
        bull = dcf3.get("bull") or {}
        rows = [
            ("BEAR", bear, "#ef4444"),
            ("BASE", base, "#f59e0b"),
            ("BULL", bull, "#10b981"),
        ]
        ivs = [(self._to_float(s.get("intrinsic_per_share")) or 0) for _, s, _ in rows]
        if not any(ivs):
            return ""
        max_iv = max(ivs) or 1

        bars = []
        for label, s, color in rows:
            iv = self._to_float(s.get("intrinsic_per_share"))
            mos = self._to_float(s.get("margin_of_safety"))
            width = (iv or 0) / max_iv * 100
            iv_str = self._fmt_cur(iv)
            mos_str = self._fmt_pct(mos) if mos is not None else "—"
            mos_color = "#10b981" if mos and mos > 0 else "#f59e0b" if mos and mos > -0.2 else "#ef4444"
            bars.append(
                f'<div style="display:grid;grid-template-columns:60px 1fr 90px 110px;'
                f'gap:10px;align-items:center;margin:8px 0;">'
                f'<div style="font-family:monospace;font-size:12px;font-weight:700;'
                f'color:{color};">{label}</div>'
                f'<div style="background:#f4f4f5;border-radius:3px;height:18px;">'
                f'<div style="background:{color};height:18px;width:{width:.1f}%;'
                f'border-radius:3px;"></div></div>'
                f'<div style="font-family:monospace;font-size:13px;font-weight:700;'
                f'text-align:right;">{iv_str}</div>'
                f'<div style="font-family:monospace;font-size:12px;color:{mos_color};'
                f'text-align:right;font-weight:600;">{mos_str} MoS</div></div>'
            )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>📊 Three-scenario DCF — intrinsic value per share</h3>
  {"".join(bars)}
  <div style="font-size:11.5px;color:#71717a;margin-top:10px;line-height:1.5">
    Each scenario tilts all assumption levers (revenue growth, terminal margin,
    WACC, capex %, tax rate) in one direction. Engine floor/ceiling bound the
    analytically defensible range.
  </div>
</div>""".strip()

    def _render_moat_detail(self, moat: Dict[str, Any]) -> str:
        """Full moat block — Helmer 7 powers + pricing-power evidence + narrative."""
        if not moat:
            return ""
        score = self._to_float(moat.get("score")) or 0
        color = "#27ae60" if score >= 7 else "#f39c12" if score >= 4 else "#c0392b"
        dims = [
            ("Cost advantage", moat.get("cost_advantage")),
            ("Network effects", moat.get("network_effects")),
            ("Switching costs", moat.get("switching_costs")),
            ("Intangibles", moat.get("intangibles")),
        ]
        dim_cells = "".join(
            f'<div style="text-align:center;">'
            f'<div style="font-family:monospace;font-size:11.5px;color:#71717a;'
            f'text-transform:uppercase;letter-spacing:0.4px;margin-bottom:4px;">{name}</div>'
            f'<div style="font-size:22px;font-weight:700;'
            f'color:{"#27ae60" if present else "#a1a1aa"};">'
            f'{"✓" if present else "—"}</div></div>'
            for name, present in dims
        )

        evidence = moat.get("evidence")
        evidence_html = (
            f'<div style="margin-top:14px;padding:12px;background:#fafafa;'
            f'border-radius:6px;font-size:13px;line-height:1.6;color:#3f3f46;'
            f'font-style:italic;">{evidence}</div>'
            if evidence else ""
        )

        pp_html = ""
        if moat.get("has_pricing_power") or moat.get("pricing_power_evidence"):
            parts = []
            if moat.get("has_pricing_power"):
                parts.append('<span style="color:#27ae60;font-weight:600">✓ Pricing power confirmed</span>')
            if moat.get("pricing_power_evidence"):
                parts.append(f'<div style="margin-top:6px;font-size:13px;line-height:1.6;">{moat["pricing_power_evidence"]}</div>')
            pp_html = (
                f'<h4 style="margin-top:14px">Pricing power evidence</h4>'
                f'{"".join(parts)}'
            )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>🏰 Moat — Helmer 7 Powers</h3>
  <div style="display:grid;grid-template-columns:160px 1fr;gap:24px;align-items:center;">
    <div style="text-align:center;">
      <div style="font-size:48px;font-weight:800;color:{color};line-height:1;">{score:.1f}</div>
      <div style="font-family:monospace;font-size:11px;color:#71717a;margin-top:6px;
                  letter-spacing:0.6px;text-transform:uppercase">/ 10</div>
    </div>
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;">
      {dim_cells}
    </div>
  </div>
  {evidence_html}
  {pp_html}
</div>""".strip()

    def _render_value_chain_detail(self, vc: Dict[str, Any]) -> str:
        """Porter Value Chain — power ratio, substitution risk, bottlenecks."""
        if not vc:
            return ""
        rows = []
        if vc.get("strategic_leverage") is not None:
            rows.append(("Strategic leverage", f"{vc['strategic_leverage']}/10"))
        if vc.get("power_ratio") is not None:
            rows.append(("Power ratio", str(vc["power_ratio"])))
        if vc.get("substitution_risk_score") is not None:
            rows.append(("Substitution risk", f"{vc['substitution_risk_score']}/10"))
        if vc.get("upstream_leak") is not None:
            rows.append(("Upstream leak",
                         "⚠ YES" if vc.get("upstream_leak") else "✓ NO"))
        if vc.get("pass_through_capability") is not None:
            rows.append(("Pass-through pricing",
                         "✓ YES" if vc.get("pass_through_capability") else "NO"))

        rows_html = "".join(
            f'<tr><td>{k}</td><td>{v}</td></tr>' for k, v in rows
        )
        table = (
            f'<table class="table-styled">{rows_html}</table>' if rows_html else ""
        )

        narrative = ""
        for label, key in [
            ("Analysis summary",         "analysis_summary"),
            ("Bottleneck analysis",      "bottleneck_analysis"),
            ("Top substitutes",          "top_substitutes"),
            ("Pricing-power assessment", "pricing_power_assessment"),
        ]:
            v = vc.get(key)
            if v:
                narrative += (
                    f'<h4 style="margin-top:14px">{label}</h4>'
                    f'<div style="font-size:13px;line-height:1.6;color:#3f3f46;">{v}</div>'
                )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>🔗 Value Chain (Porter)</h3>
  {table}
  {narrative}
</div>""".strip()

    def _render_strategic_context_detail(self, sc: Dict[str, Any]) -> str:
        """Strategic context — revenue at risk, terminal haircut, narrative."""
        if not sc:
            return ""
        rar = self._to_float(sc.get("revenue_at_risk_percent"))
        rar_str = f"{rar*100:.1f}%" if rar is not None else "—"
        rows = [
            ("Revenue at risk",   rar_str),
            ("Quality of growth", "⚠ YES" if sc.get("quality_of_growth_risk") else "✓ NO"),
            ("Terminal haircut",  "YES" if sc.get("terminal_haircut") else "NO"),
        ]
        rows_html = "".join(f'<tr><td>{k}</td><td>{v}</td></tr>' for k, v in rows)

        narrative = ""
        for label, key in [
            ("Summary",                 "summary"),
            ("Deferred-revenue trend",  "deferred_revenue_trend"),
            ("Intangible / patent risk","intangible_risk_assessment"),
        ]:
            v = sc.get(key)
            if v and len(str(v)) > 20:
                narrative += (
                    f'<h4 style="margin-top:14px">{label}</h4>'
                    f'<div style="font-size:13px;line-height:1.6;color:#3f3f46;">{v}</div>'
                )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>🧭 Strategic Context</h3>
  <table class="table-styled">{rows_html}</table>
  {narrative}
</div>""".strip()

    def _render_reverse_dcf_detail(self, p2: Dict[str, Any]) -> str:
        """Reverse-DCF horizontal-bar chart + reasons. Mirrors deep_dive_view._reverse_dcf_chart."""
        rdcf = p2.get("reverse_dcf") or {}
        if not rdcf:
            return ""
        impl = self._to_float(rdcf.get("implied_cagr_10y"))
        hist = self._to_float(rdcf.get("historical_cagr"))
        if impl is None and hist is None:
            return ""

        # Determine bar widths — scale to whichever is larger
        max_v = max(abs(impl or 0), abs(hist or 0)) or 0.01
        impl_w = ((impl or 0) / max_v) * 100
        hist_w = ((hist or 0) / max_v) * 100
        signal = (rdcf.get("signal") or "—").upper()

        def _bar(label: str, w: float, val_str: str, color: str) -> str:
            return (
                f'<div style="display:grid;grid-template-columns:120px 1fr 80px;'
                f'gap:10px;align-items:center;margin:6px 0;">'
                f'<div style="font-family:monospace;font-size:12px;color:#3f3f46;">{label}</div>'
                f'<div style="background:#f4f4f5;border-radius:3px;height:16px;">'
                f'<div style="background:{color};height:16px;width:{max(w,0):.1f}%;'
                f'border-radius:3px;"></div></div>'
                f'<div style="font-family:monospace;font-size:13px;font-weight:700;'
                f'text-align:right;">{val_str}</div></div>'
            )

        bars = _bar("Implied (market)",  impl_w, self._fmt_pct(impl), "#f59e0b") \
             + _bar("Historical (5y)",   hist_w, self._fmt_pct(hist), "#3b82f6")

        ratio_str = ""
        if impl is not None and hist and hist > 0:
            ratio = impl / hist
            ratio_color = "#c0392b" if ratio > 1.5 else "#27ae60"
            ratio_str = (
                f'<div style="font-family:monospace;font-size:12px;color:#71717a;'
                f'margin-top:6px;">Implied/Historical ratio: '
                f'<span style="color:{ratio_color};font-weight:700;">{ratio:.2f}×</span></div>'
            )

        reasons = rdcf.get("reasons") or []
        reasons_html = ""
        if reasons:
            reasons_html = (
                f'<h4 style="margin-top:14px">Why this signal</h4>'
                f'<ul style="font-size:13px;line-height:1.6;">'
                + "".join(f"<li>{r}</li>" for r in reasons) + "</ul>"
            )

        return f"""
<div class="card" style="page-break-inside:avoid">
  <h3>🔄 Reverse DCF — growth priced in</h3>
  <div style="font-family:monospace;font-size:11.5px;color:#71717a;margin-bottom:10px;">
    Signal: <strong style="color:#3f3f46;">{signal}</strong>
  </div>
  {bars}
  {ratio_str}
  {reasons_html}
</div>""".strip()

    def _render_contrarian_block(self, ca: Dict[str, Any]) -> str:
        """Contrarian bear case — bias, sentiment, bear case summary, quant challenge."""
        if not ca:
            return ""
        bias = ca.get("bias_detected", "None")
        bear = ca.get("bear_case_summary", "") or ""
        sentiment = ca.get("sentiment_score")

        sentiment_html = ""
        if isinstance(sentiment, (int, float)):
            s_color = "#c0392b" if sentiment < -3 else "#f39c12" if sentiment < 3 else "#27ae60"
            sentiment_html = (
                f' · <span style="color:{s_color};font-weight:600">sentiment {sentiment:+d}</span>'
            )

        quant = ca.get("quant_challenge") or ""
        quant_html = (
            f'<h4 style="margin-top:14px">Quantitative adversarial challenge</h4>'
            f'<div style="font-size:13px;line-height:1.6;color:#3f3f46;">{quant}</div>'
            if quant else ""
        )

        return f"""
<div class="card" style="page-break-inside:avoid;border-left:4px solid #ef4444;">
  <h3>👹 Contrarian Bear Case</h3>
  <div style="background:rgba(239,68,68,0.06);padding:14px 16px;border-radius:6px;
              font-size:13.5px;line-height:1.7;">
    <div style="margin-bottom:8px;">
      <strong style="color:#c0392b">Bias detected:</strong> {bias}{sentiment_html}
    </div>
    <div>{bear}</div>
  </div>
  {quant_html}
</div>""".strip()

    def _render_structured_thesis_md(self, ts: Dict[str, Any]) -> str:
        """Markdown twin of `_render_structured_thesis`. Returns "" when
        thesis_synthesis is absent (legacy reports pre-Phase 1.5)."""
        if not ts or not ts.get("thesis_statement"):
            return ""

        statement = ts.get("thesis_statement", "")
        confidence = (ts.get("thesis_confidence") or "—").upper()
        horizon = (ts.get("time_horizon") or "—").replace("_", " ").upper()

        out: List[str] = [
            "## 1b. 🧭 Structured Investment Thesis",
            f"**Confidence**: {confidence}  ·  **Horizon**: {horizon}",
            "",
            f"> {statement}",
            "",
        ]

        for label, key in [
            ("Bull case", "bull_case"),
            ("Base case", "base_case"),
            ("Bear case", "bear_case"),
        ]:
            cc = ts.get(key) or {}
            claim = cc.get("claim", "") or ""
            if not claim:
                continue
            cites = cc.get("cited_signals") or []
            out.append(f"### {label}")
            out.append(claim)
            if cites:
                cite_str = " · ".join(f"`{c}`" for c in cites)
                out.append(f"**Cites**: {cite_str}")
            out.append("")

        dcs = ts.get("decision_conditions") or []
        if dcs:
            out += [
                "### Decision conditions",
                "",
                "| Priority | Trigger | Observable | Action |",
                "| :--- | :--- | :--- | :--- |",
            ]
            for dc in dcs:
                pri = (dc.get("priority") or "—").upper()
                act = (dc.get("action") or "—").upper()
                trigger = (dc.get("trigger", "") or "—").replace("|", "\\|")
                obs = (dc.get("observable", "") or "—").replace("|", "\\|")
                out.append(f"| **{pri}** | {trigger} | `{obs}` | **{act}** |")
            out.append("")

        raj = ts.get("required_analyst_judgment") or []
        if raj:
            out += ["### Required analyst judgment",
                    "_Gaps the framework defers to the analyst_", ""]
            out += [f"- {r}" for r in raj]
            out.append("")

        upd = ts.get("update_conditions") or []
        if upd:
            out += ["### Update conditions",
                    "_What would invalidate this thesis_", ""]
            out += [f"- {u}" for u in upd]
            out.append("")

        # Metadata receipt at the bottom — fingerprint, coverage, citation set
        md = ts.get("_metadata") or {}
        if md:
            cov = md.get("coverage_state", "—")
            n_a = md.get("n_assessed", "?")
            n_t = md.get("n_assessable", "?")
            fp = md.get("dashboard_state_fingerprint", "")[:16]
            out += [
                f"_Generated against dashboard coverage `{cov}` ({n_a}/{n_t} dims), "
                f"fingerprint `{fp}`._",
                "",
            ]

        return "\n".join(out)

    # ─────────────────────────────────────────────────────────────────────────
    # Helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _fmt_checks_md(self, checks: List[Any]) -> str:
        if not checks:
            return "_No constitution checks available._"
        lines = []
        for check in checks:
            s = str(check)
            is_pass = "PASS" in s or "✅" in s
            is_warn = "CAUTION" in s or "⚠" in s
            icon = "✅" if is_pass else "⚠️" if is_warn else "❌"
            # Remove embedded icon characters to avoid duplication
            clean = s.replace("✅", "").replace("❌", "").replace("⚠️", "").strip()
            lines.append(f"- {icon} {clean}")
        return "\n".join(lines)

    def _fmt_ratio(self, rdcf: Dict[str, Any]) -> str:
        """Format implied/historical CAGR ratio."""
        impl = self._to_float(rdcf.get("implied_cagr_10y"))
        hist = self._to_float(rdcf.get("historical_cagr"))
        if impl is not None and hist and hist > 0:
            return f"{impl/hist:.1f}×"
        return "N/A"

    def _fmt_ratio_pct(self, val: Any) -> str:
        """
        Format a percentage value that is stored as percentage points (e.g. 18.0 not 0.18).
        Divides by 100 before applying _fmt_pct.
        This fixes the double-multiplication bug in the original HTML renderer.
        """
        v = self._to_float(val)
        if v is None:
            return "N/A"
        return self._fmt_pct(v / 100.0)

    def _fmt_bn(self, val: Any) -> str:
        """Format a value stored in billions (e.g. 94.8 → '$94.8B')."""
        v = self._to_float(val)
        if v is None:
            return "N/A"
        return f"${v:.1f}B"

    def _get_css(self) -> str:
        return """:root {
    --primary: #2c3e50; --secondary: #34495e; --accent: #e67e22;
    --bg: #ecf0f1; --card-bg: #ffffff; --text: #2c3e50;
    --pass: #27ae60; --fail: #c0392b;
}
body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background: var(--bg); color: var(--text); -webkit-print-color-adjust: exact; }
.container { max-width: 1100px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 0 20px rgba(0,0,0,0.1); }
h1, h2, h3 { color: var(--primary); border-bottom: 2px solid var(--bg); padding-bottom: 10px; }
h1 { font-size: 2.5em; margin-bottom: 0.5em; }
h2 { font-size: 1.6em; margin-top: 1.8em; color: var(--secondary); }
h4 { color: var(--secondary); margin-bottom: 8px; }
.grid-2 { display: grid; grid-template-columns: 1.5fr 1fr; gap: 20px; margin: 16px 0; }
.grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; }
.card { background: var(--card-bg); padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
.metric-box { text-align: center; padding: 10px; background: #f8f9fa; border-radius: 5px; }
.metric-val { font-size: 1.5em; font-weight: bold; display: block; }
.metric-label { font-size: 0.8em; text-transform: uppercase; color: #7f8c8d; }
.score-circle { width: 80px; height: 80px; border-radius: 50%; background: var(--primary); color: white; display: flex; align-items: center; justify-content: center; font-size: 1.4em; font-weight: bold; margin: 0 auto; }
.table-styled { width: 100%; border-collapse: collapse; margin-top: 8px; }
.table-styled th, .table-styled td { padding: 7px 8px; border-bottom: 1px solid #eee; text-align: left; font-size: 0.9em; }
.table-styled th { background: #f8f9fa; color: var(--secondary); font-weight: 600; }
.footer { margin-top: 50px; font-size: 0.8em; color: #95a5a6; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
@media print { body { background: white; } .container { box-shadow: none; padding: 0; } }"""

    @staticmethod
    def _safe_date(meta: str) -> str:
        if not meta:
            return datetime.now().strftime("%Y-%m-%d")
        return meta.split("T")[0] if "T" in meta else meta

    @staticmethod
    def _get(d: Dict[str, Any], path: Sequence[str]) -> Any:
        cur: Any = d
        for k in path:
            if not isinstance(cur, dict) or k not in cur:
                return None
            cur = cur[k]
        return cur

    @staticmethod
    def _to_float(v: Any) -> Optional[float]:
        if v is None:
            return None
        try:
            f = float(v)
            import math
            return None if math.isnan(f) else f
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _fmt_cur(v: Optional[float], decimals: int = 0) -> str:
        if v is None:
            return "N/A"
        return f"${v:,.{decimals}f}"

    @staticmethod
    def _fmt_pct(v: Optional[float]) -> str:
        if v is None:
            return "N/A"
        return f"{v:.1%}"

    @staticmethod
    def _fmt_num(v: Optional[float], decimals: int = 2) -> str:
        if v is None:
            return "N/A"
        return f"{v:,.{decimals}f}"
