"""
aletheia/utils/report_generator.py

Generates executive reports (HTML + Markdown) from the full report JSON.

Fixes vs original:
  1. Gross/FCF margin double-multiplication bug in HTML (was showing 1800%)
  2. Phase 2 valuation data (3-scenario DCF, reverse DCF, Liberti multiples)
     is now fully rendered in all three report formats
  3. Constitution checks rendered with pass/fail indicators
  4. Intrinsic value now reads from phase2_valuation (not null dcf_model)
  5. WACC reads from phase2_valuation.wacc (live computed) not dcf_model

Design rule: NEVER default missing numeric values to 0.
Missing renders as "N/A" to avoid fake 0% WACC, $0 intrinsic value.
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional, Sequence


class ReportGenerator:
    """
    Generates HTML + two Markdown reports from the Aletheia report JSON.
    All four report files written to serving/latest per ticker.
    """

    def __init__(self, output_dir: str = "valuation_data/serving/latest"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def generate_html(self, ticker: str, data: Dict[str, Any]) -> str:
        meta  = data.get("generated_at") or datetime.now().isoformat()
        econ  = data.get("1_economic_reality") or {}
        fin   = data.get("2_financial_translation") or {}
        risk  = data.get("3_capital_structure_risk") or {}
        val   = data.get("4_valuation_synthesis") or {}
        thesis = val.get("investment_thesis") or {}
        p2     = val.get("phase2_valuation") or {}

        html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Investment Report: {ticker}</title>
  <style>{self._get_css()}</style>
</head>
<body>
  <div class="container">
    {self._render_header(ticker, meta, thesis)}
    <div class="grid-2">
      {self._render_executive_summary(thesis)}
      {self._render_valuation_card(p2, risk)}
    </div>
    {self._render_phase2_section(p2)}
    {self._render_constitution(thesis)}
    {self._render_economic_engine(econ)}
    {self._render_financial_engine(fin)}
    {self._render_risk_engine(risk)}
    <div class="footer">
      Generated by Aletheia AI | {self._safe_date(meta)} | CONFIDENTIAL
    </div>
  </div>
</body>
</html>"""

        path = self.output_dir / f"{ticker}_Executive_Report.html"
        path.write_text(html, encoding="utf-8")
        return str(path)

    def generate_markdown(self, ticker: str, data: Dict[str, Any]) -> str:
        meta   = data.get("generated_at") or datetime.now().isoformat()
        econ   = data.get("1_economic_reality") or {}
        fin    = data.get("2_financial_translation") or {}
        risk   = data.get("3_capital_structure_risk") or {}
        val    = data.get("4_valuation_synthesis") or {}
        thesis = val.get("investment_thesis") or {}
        p2     = val.get("phase2_valuation") or {}

        conviction = thesis.get("conviction_score")
        narrative  = (thesis.get("narrative") or "No narrative available.").strip()

        cf     = (fin.get("clean_financials") or {})
        ratios = fin.get("ratios") or {}
        moat   = econ.get("moat") or {}
        vc     = econ.get("value_chain") or {}

        # Phase 2
        dcf3   = p2.get("three_scenario_dcf") or {}
        rdcf   = p2.get("reverse_dcf") or {}
        md_dec = p2.get("multiple_decomposition") or {}
        wacc   = self._to_float(p2.get("wacc")) or \
                 self._to_float(self._get(risk, ["capital_stack", "wacc"]))

        base   = dcf3.get("base") or {}
        bear   = dcf3.get("bear") or {}
        bull   = dcf3.get("bull") or {}

        checks = thesis.get("constitution_checks") or []

        md = f"""# 📑 Investment Memo: {ticker}
**Date**: {self._safe_date(meta)}
**Conviction Score**: {conviction} (on -10 to +10 scale)
**Status**: CONFIDENTIAL

---

## 📝 Executive Summary
{narrative}

---

## 🎯 Phase 2 Valuation — Three-Scenario DCF

| Scenario | Intrinsic Value / Share | Margin of Safety |
| :--- | :--- | :--- |
| **Bear** | {self._fmt_cur(self._to_float(bear.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(bear.get('margin_of_safety')))} |
| **Base** | {self._fmt_cur(self._to_float(base.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(base.get('margin_of_safety')))} |
| **Bull** | {self._fmt_cur(self._to_float(bull.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(bull.get('margin_of_safety')))} |

**WACC**: {self._fmt_pct(wacc)}  |  **Beta**: {self._fmt_num(self._to_float(p2.get('beta')), 2)}  |  **Rf**: {self._fmt_pct(self._to_float(p2.get('risk_free_rate')))}

### Reverse DCF — What Is the Market Pricing In?
| Metric | Value |
| :--- | :--- |
| **Implied 10-Year CAGR** | {self._fmt_pct(self._to_float(rdcf.get('implied_cagr_10y')))} |
| **Historical CAGR** | {self._fmt_pct(self._to_float(rdcf.get('historical_cagr')))} |
| **Implied / Historical** | {self._fmt_ratio(rdcf)} |
| **Signal** | {(rdcf.get('signal') or 'N/A').upper()} |

### Multiple Decomposition (Liberti Formula)
| Metric | Value |
| :--- | :--- |
| **Market EV/EBITDA** | {self._fmt_num(self._to_float(md_dec.get('market_ev_ebitda')), 1)}x |
| **Justified EV/EBITDA** | {self._fmt_num(self._to_float(md_dec.get('justified_ev_ebitda')), 1)}x |
| **Premium to Justified** | {self._fmt_pct(self._to_float(md_dec.get('premium_pct')))} |
| **ROIC-WACC Spread** | {self._fmt_pct(self._to_float(md_dec.get('roic_wacc_spread')))} |
| **Signal** | {(md_dec.get('signal') or 'N/A').upper()} |

---

## ⚖️ Constitution Checks
{self._fmt_checks_md(checks)}

---

## 1. 🌎 Economic Reality Engine
### 🏰 Moat Diagnostics
- **Moat Score**: {moat.get('score', 'N/A')}/10
- **Switching Costs**: {moat.get('switching_costs', 'N/A')}
- **Network Effects**: {moat.get('network_effects', 'N/A')}

### 🔗 Value Chain & Business Model
- **Power Ratio**: {vc.get('power_ratio', 'N/A')}
- **Upstream Value Leak**: {vc.get('upstream_leak', 'N/A')}
- **Strategic Leverage**: {vc.get('strategic_leverage', 'N/A')}

---

## 2. 💹 Financial Translation Engine (Phase 1 Cleaned)
### Core P&L (TTM)
| Item | Value |
| :--- | :--- |
| **Revenue** | {self._fmt_bn(cf.get('revenue_bn'))} |
| **EBITDA** | {self._fmt_bn(cf.get('ebitda_bn'))} |
| **FCF** | {self._fmt_bn(cf.get('fcf_bn'))} |
| **NOPAT** | {self._fmt_bn(cf.get('nopat_bn'))} |

### Balance Sheet & Efficiency
| Item | Value |
| :--- | :--- |
| **Net Debt** | {self._fmt_bn(cf.get('net_debt_bn'))} |
| **Invested Capital** | {self._fmt_bn(cf.get('invested_capital_bn'))} |
| **Gross Margin** | {self._fmt_ratio_pct(ratios.get('gross_margin_pct'))} |
| **FCF Margin** | {self._fmt_ratio_pct(ratios.get('fcf_margin_pct'))} |
| **ROIC** | {self._fmt_pct(self._to_float(ratios.get('roic')))} |

---

## 3. 🛡️ Risk & Capital Structure
- **WACC**: {self._fmt_pct(wacc)}
- **Beta**: {self._fmt_num(self._to_float(self._get(risk, ['capital_stack', 'beta'])), 2)}
- **Cost of Equity**: {self._fmt_pct(self._to_float(self._get(risk, ['capital_stack', 'cost_of_equity'])))}
"""

        path = self.output_dir / f"{ticker}_Executive_Report.md"
        path.write_text(md, encoding="utf-8")
        return str(path)

    def generate_detailed_markdown(self, ticker: str, data: Dict[str, Any]) -> str:
        meta   = data.get("generated_at") or datetime.now().isoformat()
        econ   = data.get("1_economic_reality") or {}
        fin    = data.get("2_financial_translation") or {}
        risk   = data.get("3_capital_structure_risk") or {}
        val    = data.get("4_valuation_synthesis") or {}
        thesis = val.get("investment_thesis") or {}
        p2     = val.get("phase2_valuation") or {}

        conviction = thesis.get("conviction_score")
        narrative  = (thesis.get("narrative") or "No narrative available.").strip()
        checks     = thesis.get("constitution_checks") or []

        cf     = (fin.get("clean_financials") or {})
        ratios = fin.get("ratios") or {}
        qs     = fin.get("quality_screens") or {}
        clf    = fin.get("cleaning_flags") or {}
        moat   = econ.get("moat") or {}
        vc     = econ.get("value_chain") or {}

        p2_dcf = p2.get("three_scenario_dcf") or {}
        rdcf   = p2.get("reverse_dcf") or {}
        md_dec = p2.get("multiple_decomposition") or {}
        wacc   = self._to_float(p2.get("wacc")) or \
                 self._to_float(self._get(risk, ["capital_stack", "wacc"]))

        base   = p2_dcf.get("base") or {}
        bear   = p2_dcf.get("bear") or {}
        bull   = p2_dcf.get("bull") or {}

        lines: List[str] = []

        lines += [
            f"# 📘 Detailed Valuation Report: {ticker}",
            f"**Date**: {self._safe_date(meta)}",
            "**Package**: Full Diligence",
            "**Status**: GENERATED",
            "\n---\n",
            "## 1. 📝 Investment Thesis",
            f"### Conviction Score: {conviction} (on -10 to +10 scale)",
            narrative,
            "\n---\n",
        ]

        # Phase 2 DCF
        lines += [
            "## 2. 🎯 Three-Scenario DCF (Phase 2)",
            "",
            "| Scenario | IV/Share | Margin of Safety | EV |",
            "| :--- | :--- | :--- | :--- |",
            f"| Bear | {self._fmt_cur(self._to_float(bear.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(bear.get('margin_of_safety')))} | {self._fmt_bn(self._to_float(bear.get('ev')) / 1e9 if bear.get('ev') else None)} |",
            f"| Base | {self._fmt_cur(self._to_float(base.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(base.get('margin_of_safety')))} | {self._fmt_bn(self._to_float(base.get('ev')) / 1e9 if base.get('ev') else None)} |",
            f"| Bull | {self._fmt_cur(self._to_float(bull.get('intrinsic_per_share')))} | {self._fmt_pct(self._to_float(bull.get('margin_of_safety')))} | {self._fmt_bn(self._to_float(bull.get('ev')) / 1e9 if bull.get('ev') else None)} |",
            "",
            f"**WACC (live)**: {self._fmt_pct(wacc)}",
            f"**Beta (5Y weekly vs SPY)**: {self._fmt_num(self._to_float(p2.get('beta')), 2)}",
            f"**Risk-Free Rate (^TNX)**: {self._fmt_pct(self._to_float(p2.get('risk_free_rate')))}",
            "\n---\n",
        ]

        # Reverse DCF
        impl = self._to_float(rdcf.get("implied_cagr_10y"))
        hist = self._to_float(rdcf.get("historical_cagr"))
        lines += [
            "## 3. 🔍 Reverse DCF — Market Implied Growth",
            "",
            "| Metric | Value |",
            "| :--- | :--- |",
            f"| Implied 10-Year Revenue CAGR | {self._fmt_pct(impl)} |",
            f"| Historical CAGR (robust median) | {self._fmt_pct(hist)} |",
            f"| Ratio (Implied / Historical) | {self._fmt_ratio(rdcf)} |",
            f"| Signal | {(rdcf.get('signal') or 'N/A').upper()} |",
        ]
        for reason in (rdcf.get("reasons") or []):
            lines.append(f"\n> {reason}")
        lines.append("\n---\n")

        # Multiple decomposition
        lines += [
            "## 4. 📐 Multiple Decomposition (Liberti Formula)",
            "",
            "> EV/EBITDA = [NOPAT×(1−g/ROIC)/EBITDA] ÷ (WACC−g)",
            "",
            "| Metric | Value |",
            "| :--- | :--- |",
            f"| Market EV/EBITDA | {self._fmt_num(self._to_float(md_dec.get('market_ev_ebitda')), 1)}× |",
            f"| Justified EV/EBITDA (Liberti) | {self._fmt_num(self._to_float(md_dec.get('justified_ev_ebitda')), 1)}× |",
            f"| Premium to Justified | {self._fmt_pct(self._to_float(md_dec.get('premium_pct')))} |",
            f"| ROIC | {self._fmt_pct(self._to_float(md_dec.get('roic')))} |",
            f"| WACC | {self._fmt_pct(wacc)} |",
            f"| ROIC−WACC Spread | {self._fmt_pct(self._to_float(md_dec.get('roic_wacc_spread')))} |",
            f"| Value Creation | {(md_dec.get('value_creation') or 'N/A').upper()} |",
            f"| Signal | {(md_dec.get('signal') or 'N/A').upper()} |",
            "\n---\n",
        ]

        # Constitution
        lines += [
            "## 5. ⚖️ Constitution Checks",
            "",
            self._fmt_checks_md(checks),
            "\n---\n",
        ]

        # Fundamentals
        lines += [
            "## 6. 💹 Financial Analysis (Phase 1 Cleaned)",
            "### Core P&L (TTM)",
            "| Line Item | Value |",
            "| :--- | :--- |",
            f"| Revenue | {self._fmt_bn(cf.get('revenue_bn'))} |",
            f"| EBITDA | {self._fmt_bn(cf.get('ebitda_bn'))} |",
            f"| FCF | {self._fmt_bn(cf.get('fcf_bn'))} |",
            f"| NOPAT | {self._fmt_bn(cf.get('nopat_bn'))} |",
            "",
            "### Balance Sheet",
            "| Line Item | Value |",
            "| :--- | :--- |",
            f"| Net Debt | {self._fmt_bn(cf.get('net_debt_bn'))} |",
            f"| Invested Capital | {self._fmt_bn(cf.get('invested_capital_bn'))} |",
            f"| SBC | {self._fmt_bn(cf.get('sbc_bn'))} |",
            f"| Data Quality Score | {self._fmt_num(self._to_float(cf.get('data_quality')), 2)} |",
            "",
            "### Efficiency Ratios",
            "| Ratio | Value |",
            "| :--- | :--- |",
            f"| Gross Margin | {self._fmt_ratio_pct(ratios.get('gross_margin_pct'))} |",
            f"| EBIT Margin | {self._fmt_ratio_pct(ratios.get('ebit_margin_pct'))} |",
            f"| EBITDA Margin | {self._fmt_ratio_pct(ratios.get('ebitda_margin_pct'))} |",
            f"| FCF Margin | {self._fmt_ratio_pct(ratios.get('fcf_margin_pct'))} |",
            f"| ROIC | {self._fmt_pct(self._to_float(ratios.get('roic')))} |",
            f"| ROE | {self._fmt_pct(self._to_float(ratios.get('roe')))} |",
            f"| SBC % FCF | {self._fmt_ratio_pct(ratios.get('sbc_pct_fcf'))} |",
            f"| Cash Tax Rate | {self._fmt_pct(self._to_float(ratios.get('cash_tax_rate')))} |",
            "\n---\n",
        ]

        # Domain scores
        domain_scores = qs.get("domain_scores") or {}
        if domain_scores:
            lines += [
                "## 7. 🧹 Data Cleaning Quality (9-Domain)",
                "",
                "| Domain | Score |",
                "| :--- | :--- |",
            ]
            domain_labels = {
                "D1_NonRecurring": "D1 Non-Recurring Stripping",
                "D2_JVA": "D2 JVA Separation",
                "D3_EBITNorm": "D3 EBIT Normalization",
                "D4_AccountingPolicy": "D4 Accounting Policy",
                "D5_Lease": "D5 Lease Normalization",
                "D6_Pension": "D6 Pension Cleaning",
                "D7_SBC": "D7 SBC Adjustment",
                "D8_Revenue": "D8 Revenue Recognition",
                "D9_WorkingCapital": "D9 Working Capital",
                "D10_Tax": "D10 Tax Sustainability",
            }
            for key, score in sorted(domain_scores.items()):
                label = domain_labels.get(key, key)
                score_v = self._to_float(score)
                icon = "✅" if score_v and score_v >= 0.9 else "⚠️" if score_v and score_v >= 0.7 else "❌"
                lines.append(f"| {icon} {label} | {self._fmt_num(score_v, 2)} |")

            warn  = clf.get("warning_count", 0)
            err   = clf.get("error_count", 0)
            lines += ["", f"**Warnings**: {warn}  |  **Errors**: {err}", "\n---\n"]

        # Economic reality
        lines += [
            "## 8. 🌎 Economic Reality & Moat",
            f"### Moat Score: {moat.get('score', 'N/A')}/10",
            f"- Switching Costs: {moat.get('switching_costs', 'N/A')}",
            f"- Network Effects: {moat.get('network_effects', 'N/A')}",
            "",
            "### Value Chain",
            f"- Power Ratio: {vc.get('power_ratio', 'N/A')}",
            f"- Upstream Value Leak: {vc.get('upstream_leak', 'N/A')}",
            f"- Strategic Leverage: {vc.get('strategic_leverage', 'N/A')}",
            "\n---\n",
        ]

        # Capital structure
        cap = risk.get("capital_stack") or {}
        rf_data = risk.get("risk_factors") or {}
        liq = rf_data.get("liquidity") or {}
        lines += [
            "## 9. 🛡️ Capital Structure & Risk",
            f"- WACC: {self._fmt_pct(self._to_float(cap.get('wacc')))}",
            f"- Cost of Equity: {self._fmt_pct(self._to_float(cap.get('cost_of_equity')))}",
            f"- Beta: {self._fmt_num(self._to_float(cap.get('beta')), 2)}",
            f"- Liquidity Alert: {liq.get('liquidity_alert', False)}",
            f"- Refinancing Risk Score: {liq.get('refinancing_risk_score', 'N/A')}/10",
        ]

        md = "\n".join(lines)
        path = self.output_dir / f"{ticker}_Detailed_Report.md"
        path.write_text(md, encoding="utf-8")
        return str(path)

    # ─────────────────────────────────────────────────────────────────────────
    # HTML section renderers
    # ─────────────────────────────────────────────────────────────────────────

    def _render_header(self, ticker: str, meta: str, thesis: Dict[str, Any]) -> str:
        conviction = thesis.get("conviction_score")
        conv_num   = int(conviction) if conviction is not None else 0
        color = "#27ae60" if conv_num >= 3 else "#f39c12" if conv_num >= 0 else "#c0392b"
        return f"""
<div style="display:flex;justify-content:space-between;align-items:center">
  <div>
    <h1>{ticker} Investment Memo</h1>
    <div style="color:#7f8c8d">Generated on {self._safe_date(meta)}</div>
  </div>
  <div style="text-align:center">
    <div class="score-circle" style="background:{color}">{conv_num:+d}</div>
    <div style="margin-top:5px;font-weight:bold">CONVICTION</div>
  </div>
</div>""".strip()

    def _render_executive_summary(self, thesis: Dict[str, Any]) -> str:
        narrative = (thesis.get("narrative") or "No narrative available.").replace("\n", "<br>")
        return f"""
<div class="card">
  <h3>📝 Executive Summary</h3>
  <p style="line-height:1.6">{narrative}</p>
</div>""".strip()

    def _render_valuation_card(self, p2: Dict[str, Any], risk: Dict[str, Any]) -> str:
        dcf3 = p2.get("three_scenario_dcf") or {}
        base = dcf3.get("base") or {}
        bear = dcf3.get("bear") or {}
        bull = dcf3.get("bull") or {}
        base_iv  = self._to_float(base.get("intrinsic_per_share"))
        base_mos = self._to_float(base.get("margin_of_safety"))
        wacc = self._to_float(p2.get("wacc")) or \
               self._to_float(self._get(risk, ["capital_stack", "wacc"]))
        rdcf = p2.get("reverse_dcf") or {}
        impl = self._to_float(rdcf.get("implied_cagr_10y"))
        hist = self._to_float(rdcf.get("historical_cagr"))

        mos_color = "green" if base_mos and base_mos > 0 else "red"

        return f"""
<div class="card">
  <h3>🎯 Valuation Synthesis (Phase 2)</h3>
  <div class="metric-box" style="margin-bottom:10px">
    <span class="metric-val" style="color:{mos_color}">{self._fmt_pct(base_mos)}</span>
    <span class="metric-label">Base Margin of Safety</span>
  </div>
  <table class="table-styled">
    <tr><td>Bear IV / Share</td><td style="font-weight:bold">{self._fmt_cur(self._to_float(bear.get('intrinsic_per_share')))}</td></tr>
    <tr><td>Base IV / Share</td><td style="font-weight:bold;color:{mos_color}">{self._fmt_cur(base_iv)}</td></tr>
    <tr><td>Bull IV / Share</td><td style="font-weight:bold">{self._fmt_cur(self._to_float(bull.get('intrinsic_per_share')))}</td></tr>
    <tr><td>WACC (live)</td><td>{self._fmt_pct(wacc)}</td></tr>
    <tr><td>Implied CAGR</td><td>{self._fmt_pct(impl)}</td></tr>
    <tr><td>Historical CAGR</td><td>{self._fmt_pct(hist)}</td></tr>
  </table>
</div>""".strip()

    def _render_phase2_section(self, p2: Dict[str, Any]) -> str:
        rdcf   = p2.get("reverse_dcf") or {}
        md_dec = p2.get("multiple_decomposition") or {}

        impl   = self._to_float(rdcf.get("implied_cagr_10y"))
        hist   = self._to_float(rdcf.get("historical_cagr"))
        signal = (rdcf.get("signal") or "").upper()

        ev_market = self._to_float(md_dec.get("market_ev_ebitda"))
        ev_just   = self._to_float(md_dec.get("justified_ev_ebitda"))
        premium   = self._to_float(md_dec.get("premium_pct"))
        spread    = self._to_float(md_dec.get("roic_wacc_spread"))
        vc_signal = (md_dec.get("signal") or "").upper()

        spread_color = "#27ae60" if spread and spread > 0 else "#c0392b"
        prem_color   = "#c0392b" if premium and premium > 0 else "#27ae60"

        reasons_html = "".join(
            f"<li style='margin-bottom:6px'>{r}</li>"
            for r in (rdcf.get("reasons") or [])
        )

        return f"""
<h2>Phase 2: Quantitative Valuation Intelligence</h2>
<div class="grid-2">
  <div class="card">
    <h4>🔍 Reverse DCF — What Is the Market Pricing In?</h4>
    <table class="table-styled">
      <tr><td>Implied 10Y CAGR</td><td style="font-weight:bold">{self._fmt_pct(impl)}</td></tr>
      <tr><td>Historical CAGR</td><td>{self._fmt_pct(hist)}</td></tr>
      <tr><td>Ratio (Impl/Hist)</td><td style="color:{('#c0392b' if impl and hist and impl/hist > 1.5 else '#27ae60')}">{self._fmt_ratio(rdcf)}</td></tr>
      <tr><td>Signal</td><td><b>{signal}</b></td></tr>
    </table>
    {"<ul style='font-size:0.85em;padding-left:18px;margin-top:10px;color:#555'>" + reasons_html + "</ul>" if reasons_html else ""}
  </div>
  <div class="card">
    <h4>📐 Multiple Decomposition (Liberti Formula)</h4>
    <div style="font-size:0.8em;color:#888;margin-bottom:8px">
      EV/EBITDA = [NOPAT×(1−g/ROIC)/EBITDA] ÷ (WACC−g)
    </div>
    <table class="table-styled">
      <tr><td>Market EV/EBITDA</td><td style="font-weight:bold">{self._fmt_num(ev_market, 1)}×</td></tr>
      <tr><td>Justified EV/EBITDA</td><td style="color:#27ae60">{self._fmt_num(ev_just, 1)}×</td></tr>
      <tr><td>Premium to Justified</td><td style="color:{prem_color}">{self._fmt_pct(premium)}</td></tr>
      <tr><td>ROIC−WACC Spread</td><td style="color:{spread_color}">{self._fmt_pct(spread)}</td></tr>
      <tr><td>Signal</td><td><b>{vc_signal}</b></td></tr>
    </table>
  </div>
</div>""".strip()

    def _render_constitution(self, thesis: Dict[str, Any]) -> str:
        checks = thesis.get("constitution_checks") or []
        if not checks:
            return ""

        rows = ""
        for check in checks:
            check_str = str(check)
            is_pass   = "PASS" in check_str or "✅" in check_str
            is_warn   = "CAUTION" in check_str or "⚠" in check_str
            bg     = "#d5f5e3" if is_pass else "#fef9e7" if is_warn else "#fadbd8"
            border = "#27ae60" if is_pass else "#f39c12" if is_warn else "#c0392b"
            icon   = "✅" if is_pass else "⚠️" if is_warn else "❌"
            # Clean up unicode escape sequences
            clean = check_str.replace("✅", "").replace("❌", "").replace("⚠️", "").strip()
            rows += f"""<tr style="background:{bg};border-left:4px solid {border}">
              <td style="padding:8px 6px;font-size:1.3em">{icon}</td>
              <td style="padding:8px">{clean}</td>
            </tr>"""

        return f"""
<h2>⚖️ Constitution Compliance</h2>
<div class="card" style="padding:0;overflow:hidden">
  <table class="table-styled" style="margin:0">
    <thead><tr>
      <th style="width:40px"></th>
      <th>Check</th>
    </tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>""".strip()

    def _render_economic_engine(self, econ: Dict[str, Any]) -> str:
        moat = econ.get("moat") or {}
        vc   = econ.get("value_chain") or {}
        ind  = econ.get("industry_structure") or {}

        moat_score = int(moat.get("score") or 0)
        moat_color = "#27ae60" if moat_score >= 9 else "#f39c12" if moat_score >= 7 else "#c0392b"

        return f"""
<h2>1. 🌎 Economic Reality Engine</h2>
<div class="grid-3">
  <div class="card">
    <h4>🏰 Moat Assessment</h4>
    <div class="metric-box">
      <span class="metric-val" style="color:{moat_color}">{moat_score}/10</span>
      <span class="metric-label">Moat Score (Helmer 7 Powers)</span>
    </div>
    <ul style="font-size:0.9em;padding-left:20px;margin-top:10px">
      <li>Switching Costs: <b>{moat.get('switching_costs', 'N/A')}</b></li>
      <li>Network Effects: <b>{moat.get('network_effects', 'N/A')}</b></li>
    </ul>
  </div>
  <div class="card">
    <h4>🔗 Value Chain (Porter)</h4>
    <table class="table-styled">
      <tr><td>Power Ratio</td><td>{vc.get('power_ratio', 'N/A')}</td></tr>
      <tr><td>Upstream Leak</td>
        <td style="color:{'#c0392b' if vc.get('upstream_leak') else '#27ae60'}">
          {'⚠ YES' if vc.get('upstream_leak') else '✓ NO'}
        </td>
      </tr>
      <tr><td>Strategic Leverage</td><td>{vc.get('strategic_leverage', 'N/A')}</td></tr>
    </table>
  </div>
  <div class="card">
    <h4>📊 Industry Structure</h4>
    <table class="table-styled">
      <tr><td>Cyclicality Z-Score</td><td>{self._fmt_num(self._to_float(ind.get('cyclicality_z_score')), 2)}</td></tr>
      <tr><td>At Cyclical Peak</td>
        <td style="color:{'#c0392b' if ind.get('is_peak') else '#27ae60'}">
          {'⚠ YES' if ind.get('is_peak') else '✓ NO'}
        </td>
      </tr>
    </table>
  </div>
</div>""".strip()

    def _render_financial_engine(self, fin: Dict[str, Any]) -> str:
        cf     = (fin.get("clean_financials") or {})
        ratios = fin.get("ratios") or {}
        qs     = fin.get("quality_screens") or {}

        # FIX: gross_margin_pct is stored as % (e.g. 18.0), not decimal.
        # _fmt_ratio_pct handles this correctly — divides by 100 before formatting.
        return f"""
<h2>2. 💹 Financial Translation (Phase 1 Cleaned)</h2>
<div class="card">
  <div class="grid-3">
    <div>
      <h4>Core P&L (TTM)</h4>
      <table class="table-styled">
        <tr><td>Revenue</td><td>{self._fmt_bn(cf.get('revenue_bn'))}</td></tr>
        <tr><td>EBITDA</td><td>{self._fmt_bn(cf.get('ebitda_bn'))}</td></tr>
        <tr><td>FCF</td><td>{self._fmt_bn(cf.get('fcf_bn'))}</td></tr>
        <tr><td>NOPAT</td><td>{self._fmt_bn(cf.get('nopat_bn'))}</td></tr>
      </table>
    </div>
    <div>
      <h4>Balance Sheet</h4>
      <table class="table-styled">
        <tr><td>Net Debt</td><td>{self._fmt_bn(cf.get('net_debt_bn'))}</td></tr>
        <tr><td>Invested Capital</td><td>{self._fmt_bn(cf.get('invested_capital_bn'))}</td></tr>
        <tr><td>SBC</td><td>{self._fmt_bn(cf.get('sbc_bn'))}</td></tr>
      </table>
    </div>
    <div>
      <h4>Efficiency Ratios</h4>
      <table class="table-styled">
        <tr><td>Gross Margin</td><td>{self._fmt_ratio_pct(ratios.get('gross_margin_pct'))}</td></tr>
        <tr><td>EBIT Margin</td><td>{self._fmt_ratio_pct(ratios.get('ebit_margin_pct'))}</td></tr>
        <tr><td>FCF Margin</td><td>{self._fmt_ratio_pct(ratios.get('fcf_margin_pct'))}</td></tr>
        <tr><td>ROIC</td><td>{self._fmt_pct(self._to_float(ratios.get('roic')))}</td></tr>
        <tr><td>ROE</td><td>{self._fmt_pct(self._to_float(ratios.get('roe')))}</td></tr>
      </table>
    </div>
  </div>
</div>""".strip()

    def _render_risk_engine(self, risk: Dict[str, Any]) -> str:
        cap = risk.get("capital_stack") or {}
        rf  = (risk.get("risk_factors") or {}).get("liquidity") or {}
        ds  = (risk.get("risk_factors") or {}).get("downside") or {}

        return f"""
<h2>3. 🛡️ Capital Structure & Risk</h2>
<div class="grid-2">
  <div class="card">
    <h4>💰 Capital Stack</h4>
    <table class="table-styled">
      <tr><td>WACC</td><td>{self._fmt_pct(self._to_float(cap.get('wacc')))}</td></tr>
      <tr><td>Cost of Equity</td><td>{self._fmt_pct(self._to_float(cap.get('cost_of_equity')))}</td></tr>
      <tr><td>Beta</td><td>{self._fmt_num(self._to_float(cap.get('beta')), 2)}</td></tr>
    </table>
    <h4 style="margin-top:12px">⚠️ Liquidity</h4>
    <table class="table-styled">
      <tr><td>Liquidity Alert</td>
        <td style="color:{'#c0392b' if rf.get('liquidity_alert') else '#27ae60'}">
          {'⚠ YES' if rf.get('liquidity_alert') else '✓ NO'}
        </td>
      </tr>
      <tr><td>Refinancing Risk</td><td>{rf.get('refinancing_risk_score', 'N/A')}/10</td></tr>
    </table>
  </div>
  <div class="card">
    <h4>📉 Downside Protection</h4>
    <table class="table-styled">
      <tr><td>Tangible Book Value</td><td>{self._fmt_cur(self._to_float(ds.get('tangible_book_value')))}</td></tr>
      <tr><td>Earnings Power Value</td><td>{self._fmt_cur(self._to_float(ds.get('earnings_power_value')))}</td></tr>
      <tr><td>Floor Value</td><td>{self._fmt_cur(self._to_float(ds.get('floor_value')))}</td></tr>
    </table>
  </div>
</div>""".strip()

    # ─────────────────────────────────────────────────────────────────────────
    # Helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _fmt_checks_md(self, checks: List[Any]) -> str:
        if not checks:
            return "_No constitution checks available._"
        lines = []
        for check in checks:
            s = str(check)
            is_pass = "PASS" in s or "✅" in s
            is_warn = "CAUTION" in s or "⚠" in s
            icon = "✅" if is_pass else "⚠️" if is_warn else "❌"
            # Remove embedded icon characters to avoid duplication
            clean = s.replace("✅", "").replace("❌", "").replace("⚠️", "").strip()
            lines.append(f"- {icon} {clean}")
        return "\n".join(lines)

    def _fmt_ratio(self, rdcf: Dict[str, Any]) -> str:
        """Format implied/historical CAGR ratio."""
        impl = self._to_float(rdcf.get("implied_cagr_10y"))
        hist = self._to_float(rdcf.get("historical_cagr"))
        if impl is not None and hist and hist > 0:
            return f"{impl/hist:.1f}×"
        return "N/A"

    def _fmt_ratio_pct(self, val: Any) -> str:
        """
        Format a percentage value that is stored as percentage points (e.g. 18.0 not 0.18).
        Divides by 100 before applying _fmt_pct.
        This fixes the double-multiplication bug in the original HTML renderer.
        """
        v = self._to_float(val)
        if v is None:
            return "N/A"
        return self._fmt_pct(v / 100.0)

    def _fmt_bn(self, val: Any) -> str:
        """Format a value stored in billions (e.g. 94.8 → '$94.8B')."""
        v = self._to_float(val)
        if v is None:
            return "N/A"
        return f"${v:.1f}B"

    def _get_css(self) -> str:
        return """:root {
    --primary: #2c3e50; --secondary: #34495e; --accent: #e67e22;
    --bg: #ecf0f1; --card-bg: #ffffff; --text: #2c3e50;
    --pass: #27ae60; --fail: #c0392b;
}
body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background: var(--bg); color: var(--text); -webkit-print-color-adjust: exact; }
.container { max-width: 1100px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 0 20px rgba(0,0,0,0.1); }
h1, h2, h3 { color: var(--primary); border-bottom: 2px solid var(--bg); padding-bottom: 10px; }
h1 { font-size: 2.5em; margin-bottom: 0.5em; }
h2 { font-size: 1.6em; margin-top: 1.8em; color: var(--secondary); }
h4 { color: var(--secondary); margin-bottom: 8px; }
.grid-2 { display: grid; grid-template-columns: 1.5fr 1fr; gap: 20px; margin: 16px 0; }
.grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; }
.card { background: var(--card-bg); padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
.metric-box { text-align: center; padding: 10px; background: #f8f9fa; border-radius: 5px; }
.metric-val { font-size: 1.5em; font-weight: bold; display: block; }
.metric-label { font-size: 0.8em; text-transform: uppercase; color: #7f8c8d; }
.score-circle { width: 80px; height: 80px; border-radius: 50%; background: var(--primary); color: white; display: flex; align-items: center; justify-content: center; font-size: 1.4em; font-weight: bold; margin: 0 auto; }
.table-styled { width: 100%; border-collapse: collapse; margin-top: 8px; }
.table-styled th, .table-styled td { padding: 7px 8px; border-bottom: 1px solid #eee; text-align: left; font-size: 0.9em; }
.table-styled th { background: #f8f9fa; color: var(--secondary); font-weight: 600; }
.footer { margin-top: 50px; font-size: 0.8em; color: #95a5a6; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
@media print { body { background: white; } .container { box-shadow: none; padding: 0; } }"""

    @staticmethod
    def _safe_date(meta: str) -> str:
        if not meta:
            return datetime.now().strftime("%Y-%m-%d")
        return meta.split("T")[0] if "T" in meta else meta

    @staticmethod
    def _get(d: Dict[str, Any], path: Sequence[str]) -> Any:
        cur: Any = d
        for k in path:
            if not isinstance(cur, dict) or k not in cur:
                return None
            cur = cur[k]
        return cur

    @staticmethod
    def _to_float(v: Any) -> Optional[float]:
        if v is None:
            return None
        try:
            f = float(v)
            import math
            return None if math.isnan(f) else f
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _fmt_cur(v: Optional[float], decimals: int = 0) -> str:
        if v is None:
            return "N/A"
        return f"${v:,.{decimals}f}"

    @staticmethod
    def _fmt_pct(v: Optional[float]) -> str:
        if v is None:
            return "N/A"
        return f"{v:.1%}"

    @staticmethod
    def _fmt_num(v: Optional[float], decimals: int = 2) -> str:
        if v is None:
            return "N/A"
        return f"{v:,.{decimals}f}"
